import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Voting Dapp</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto'>
				<div className='mt-8'>
					<nav className=' flex justify-between items-center'>
						<Link href='/'>
							<a href='#' className='text-2xl font-bold'>
								Voting Dapp
							</a>
						</Link>
						<button className='bg-[#4B60B0] flex items-center justify-center text-white rounded-md uppercase px-5 py-3 hover:bg-slate-900'>
							connect
						</button>
					</nav>
					<section className='flex items-center justify-between mt-32'>
						<div className='flex flex-col items-center'>
							<h3 className='text-4xl font-bold text-black my-4'>Start voting in minutes</h3>
							<p className='text-base text-gray-400 mb-4 text-left'>Vote for your preferred candidate</p>
							<button className='bg-[#4B60B0] flex items-center justify-center text-white rounded-md uppercase px-5 py-3 hover:bg-slate-900'>
								get started
							</button>
						</div>
						<div>
							<Image src='/images/1.png' alt='' height='500' width='600' />
						</div>
					</section>
				</div>
			</main>
		</div>
	);
};

export default Home;
